### ISSUE TITLE
Track User Progress In Courses

### ISSUE THREAD

**Issue by Sn00pyW00dst0ck** [RyleyGG/apluschiever#22]
### Issue Description
Create a way to track user progress through a course. The user should be able to view their progress through a course (perhaps nodes show up a different color). 

### Proposed Implementation
Modify the database so that each user has a nodes completed which references course nodes so we can track/get progress that way. Update the frontend UI to show the user their completion statistics and allow them to filter based on completed/uncompleted nodes.

**Comment by RyleyGG** [comment]
functionality implemented, closing
