### ISSUE TITLE
Implement OAuth2 In Frontend

### ISSUE THREAD

**Issue by Sn00pyW00dst0ck** [RyleyGG/apluschiever#23]
### Issue Description
Implement an OAuth2 login workflow within the frontend web app.

### Proposed Implementation
Create an authentication module with an interceptor, login service, and other required components to setup the OAuth2 login workflow.

**Comment by RyleyGG** [comment]
Note: the interceptor needs to catch 401 errors that result from access token expiration and, if the refresh token is valid, automatically generate a new access token in the background without disrupting user flow.
