### ISSUE TITLE
Create Lesson Page Skeleton

### ISSUE THREAD

**Issue by RyleyGG** [RyleyGG/apluschiever#33]
### Issue Description
When the user clicks on a course node, the lesson view should pop up (either a modal? or a new page altogether?) with some placeholder content. The lesson view also needs to support templatized layouts of content to support different content decisions by teachers and layout preferences by students.

### Proposed Implementation
See Above. Utilize PrimeNG library for advanced UI requirements.

**Comment by Sn00pyW00dst0ck** [comment]
re-considering
