### ISSUE TITLE
Create users/me endpoint

### ISSUE THREAD

**Issue by Sn00pyW00dst0ck** [RyleyGG/apluschiever#46]
### Issue Description
Create an endpoint to get the currently logged in user information. 

### Proposed Implementation
Create a new route in the users router to get this data. 

This route is will help simplify frontend development efforts. We don't want to be filtering users by user id all the time, especially if it can easily be gotten from the backend with a simple get request.

**Comment by RyleyGG** [comment]
closed via #56
